# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Brown Lab SOuP
email: jonbrig@vt.edu
description: >- # this means to ignore newlines until "baseurl:"
  SOPs are modular materials that, if followed, help guide the production of standardized, replicable research. Written by the Brown Lab.
url: "https://brown-and-briganti.github.io"
baseurl: "/sops"
repository: "brown-and-briganti/sops"

#baseurl: "" # the subpath of your site, e.g. /blog
#url: https://brown-and-briganti.github.io/sops.github.io # the base hostname & protocol for your site, e.g. http://example.com
#repository: "brown-and-briganti/sops.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.27.1
minimal_mistakes_skin: "air"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

include:
  - _pages

after_footer_scripts:
  - /assets/js/tablist-script.js
  - https://cdn.jsdelivr.net/npm/mermaid@11.7.0/dist/mermaid.js
  - /assets/js/mermaid.js


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
